{
 "title": "Pizza Dashboard",
 "time": { "from": "now-30m", "to": "now-10m" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Logs",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{component=\"jwt-pizza-service\"} | json"
    }
   ]
  },
  {
   "title": "Average Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "avg_over_time(average_request_latency_ms_milliseconds{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Average Latency (ms)"
    }
   ]
  },
  {
   "title": "HTTP Requests / Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "sum(rate(requests_total{source=\"jwt-pizza-service\"}[1m])) * 60",
     "legendFormat": "Total"
    },
    {
     "expr": "sum by(method) (rate(requests_total{source=\"jwt-pizza-service\", method=\"PUT\"}[1m]) * 60)",
     "legendFormat": "{{method}}"
    },
    {
     "expr": "sum by(method) (rate(requests_total{source=\"jwt-pizza-service\", method=\"GET\"}[1m]) * 60)",
     "legendFormat": "{{method}}"
    },
    {
     "expr": "sum by(method) (rate(requests_total{source=\"jwt-pizza-service\", method=\"POST\"}[1m]) * 60)",
     "legendFormat": "{{method}}"
    },
    {
     "expr": "sum by(method) (rate(requests_total{source=\"jwt-pizza-service\", method=\"DELETE\"}[1m]) * 60)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Pizza Creation Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "rate(pizza_creation_latency_milliseconds_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Latency (ms)"
    }
   ]
  },
  {
   "title": "Active Users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "active_users_total{source=\"jwt-pizza-service\"}",
     "legendFormat": "Active Users"
    }
   ]
  },
  {
   "title": "Pizzas Sold / Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "rate(pizzas_sold_total{source=\"jwt-pizza-service\"}[1m]) * 60",
     "legendFormat": "Pizzas Sold"
    }
   ]
  },
  {
   "title": "Authentications",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "rate(login_success_total{source=\"jwt-pizza-service\"}[1m]) * 60",
     "legendFormat": "Success"
    },
    {
     "expr": "rate(login_failed_total{source=\"jwt-pizza-service\"}[1m]) * 60",
     "legendFormat": "Failure"
    }
   ]
  },
  {
   "title": "Revenue / Minute",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "currencyBTC" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(revenue_USD_total{source=\"jwt-pizza-service\"}[1m]) * 60",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "System",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_cpu_usage_percent{source=\"jwt-pizza-service\"}",
     "legendFormat": "CPU"
    },
    {
     "expr": "system_memory_usage_percent{source=\"jwt-pizza-service\"}",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "Pizza Creation Failures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "changes(pizza_creation_failures_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Failures"
    }
   ]
  }
 ]
}